### ISSUE TITLE
Question - fabricjs browser only 

### ISSUE THREAD

**Issue by niftyminer** [asotog/fabricjs-react#10]
Hey, thanks for this project, it really makes integrating fabricjs easier with React. My issue is not directly related to fabricjs-react, but setting it up generally. Namely that I have to use it in a browser only setup (nextjs), but it has native dependencies which fail on `next build`. I've checked out the issues in `fabricjs` but there seem to be little will to support this use-case properly, I've also found `fabricjs-pure-browser` on npm which tries to solve it but I have other build issues there. Do you have experience setting it up for a browser only environment?

Thanks

**Comment by asotog** [comment]
@niftyminer  haven't try on nextjs/ssr environment, but I feel this is a good suggestion, for us to try there

**Comment by asotog** [comment]
since fabricjs would be only needed on browser side you can try this https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
