### ISSUE TITLE
Fabric v5 ?

### ISSUE THREAD

**Issue by ajoslin103** [asotog/fabricjs-react#12]
Your library is pinned to Fabric v4

I'm going to try it with Fabric v5 using --force on the install

I'll report back here w/results

(Fabric says no real breaking changes in v5 http://fabricjs.com/changelog)

**Comment by john-revzoom** [comment]
is there any chance moving for fabric 5 soon?

**Comment by asotog** [comment]
yeaa we’ll look soon 


Sent from Yahoo Mail for iPhone


On Saturday, October 29, 2022, 9:14 AM, john-revzoom ***@***.***> wrote:




is there any chance moving for fabric 5 soon?

**Comment by john-revzoom** [comment]
> yeaa we’ll look soon  Sent from Yahoo Mail for iPhone On Saturday, October 29, 2022, 9:14 AM, john-revzoom ***@***.***> wrote: is there any chance moving for fabric 5 soon? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Thanks a lot

**Comment by asotog** [comment]
v1.2.0 released supporting FabricJS v5

**Comment by ajoslin103** [comment]
thank you so much !! 

I can't believe how much effort it takes to get the smallest things done these days

I don't know where you found the time, I'm super-glad you did !!

thanks!!
