### ISSUE TITLE
canvas.on events fires two times

### ISSUE THREAD

**Issue by lucker2120** [asotog/fabricjs-react#13]
Hello, I've tried to add own listeners to editor.canvas, but faced this issue. Events fires two times for some reason. 
Here is codesandbox where you can reproduce the problem: https://codesandbox.io/s/relaxed-wescoff-nstd6u?file=/src/App.js

**Comment by asotog** [comment]
@lucker2120 hey, thanks for reaching out, I think this is expected, mouse up and down are 2 different events, then log will show up 2 times

**Comment by lucker2120** [comment]
@asotog, No-no, I mean, when you click left mouse button one time => mouse:down fires two times and then mouse:up fires two times

**Comment by asotog** [comment]
@lucker2120  I think you will need to wrap the event attachment in a useEffect maybe, your code is attaching the same event many times
```
 useEffect(() => {
    function mouseUp() {
      console.log("mouse:up");
    }
    function mouseDown() {
      console.log("mouse:down");
    }
    if (editor) {
      editor.canvas.on("mouse:down", mouseDown);
      editor.canvas.on("mouse:up", mouseUp);
    }
    return () => {
      if (editor.canvas) {
        editor.canvas.off("mouse:down", mouseDown);
        editor.canvas.off("mouse:up", mouseUp);
      }
    };
}, [editor]);
```
