### ISSUE TITLE
how can i change font size by progressbar please help me also want to make font bold italic underline

### ISSUE THREAD

**Issue by abhishekvnnovate** [asotog/fabricjs-react#14]

**Comment by abhishekvnnovate** [comment]
fabric.Image.fromURL("https://i.imgur.com/8zvUjul.jpg", function (oImg) {
    editor?.canvas.add(oImg);
  });

**Comment by asotog** [comment]
can you please share screenshot or code sample how to reproduce ?

**Comment by asotog** [comment]
closing, no feedback provided
