### ISSUE TITLE
How can I create multiple canvases and use them on single page.

### ISSUE THREAD

**Issue by abhishekvnnovate** [asotog/fabricjs-react#17]

**Comment by abhishekvnnovate** [comment]
hello dear owner please attach solution.

**Comment by abhishekvnnovate** [comment]
> @abhishekvnnovate can you give a sandbox example ? I would say you can have 2 components e.g Canvas1 and Canvas2, then inside each you initialize fabric separate

yes right i want to use canvas1 and canvas2 and then each canvas i wan to initialize febric seprate.

for example i want to add text on both canvas1 and canvas2.

I was working on book cover project there is front-cover and back-cover so i am using both canvas with single toolbar.

**Comment by Seun-Oyediran** [comment]
Please has anyone found a solution
I need to have 4 different canvas on a page

**Comment by asotog** [comment]
@Seun-Oyediran in the same way as described before, you can have 4 components each of them handing its own canvas and fabricjs instance

**Comment by asotog** [comment]
> @Seun-Oyediran in the same way as described before, you can have 4 components each of them handing its own canvas and fabricjs instance

but if you are thinking to have 4 canvas in the same component, that is not possible, you have to split in different components
