### ISSUE TITLE
How do I download the images I add to the canvas

### ISSUE THREAD

**Issue by Fortune-Muhumuza** [asotog/fabricjs-react#18]
I'd like to create a function that when called creates an image file that I can save or download and be able to load for later use

**Comment by jakesteelman** [comment]
You can call the canvas instance's toDataURL method and pass in some options for the download. There may be a more efficient/easier way to do this, but I just create an anchor on the DOM, set the `href` and `download` attributes, call the `click()` method on it, then remove it with the `remove()` method. Hope this helps!

```
const url = editor?.canvas.toDataURL({ format: 'png' })
const dl = document.createElement('a')
dl.href = url
dl.dowload = 'filename'
dl.click()
dl.remove()
```

**Comment by asotog** [comment]
yeah you can access fabricjs canvas from editor object, if you need to follow official documentation http://fabricjs.com/

**Comment by asotog** [comment]
closing due inactivity
