### ISSUE TITLE
Latest FabricJS?

### ISSUE THREAD

**Issue by emorling** [asotog/fabricjs-react#2]
Nice! Can we bump this to the latest fabric js version?

**Comment by asotog** [comment]
That will be nice, I can try


Sent from Yahoo Mail for iPhone


On Saturday, February 20, 2021, 7:46 AM, emorling <notifications@github.com> wrote:




Nice! Can we bump this to the latest fabric js version?

**Comment by emorling** [comment]
I need to add the ability to add an image to the editor.

For example:

`fabric.Image.fromURL('https://images.pexels.com/photos/390051/surfer-wave-sunset-the-indian-ocean-390051.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', (oImg) => {
      // scale image down, and flip it, before adding it onto canvas
      oImg.scale(0.5).set('flipX', true);
      editor.add(oImg);
    });
`

Is there a way to access the fabric object? Or should we be approaching this in another way?

**Comment by asotog** [comment]
closing this, using the latest fabric and react versions `1.0.8`

**Comment by ct-gilford** [comment]
> closing this, using the latest fabric and react versions on `1.0.8`

Is it using the latest fabric version 4.5.0?

**Comment by asotog** [comment]
hey @ct-gilford on the peer dependencies we define : 
```
"peerDependencies": {
    "fabric": "^4.3.1",
  ...
```
I believe based on [semver](https://devhints.io/semver) definition it should allow you to use 4.5.0



> > closing this, using the latest fabric and react versions on `1.0.8`
> 
> Is it using the latest fabric version 4.5.0?
