### ISSUE TITLE
Is it possible to change border-radius?

### ISSUE THREAD

**Issue by katungi** [asotog/fabricjs-react#20]
Hey @asotog , I am trying to create a way to change the border radius of a rectangle, is it possible?

**Comment by asotog** [comment]
what do you mean by changing default corners with rounded corners?

**Comment by katungi** [comment]
Hey @asotog , yes that's what I meant. And to alter the border radius of the rounded corners

**Comment by asotog** [comment]
@katungi  not sure,  wondered if fabricjs supports that
