### ISSUE TITLE
Upgrade to react18

### ISSUE THREAD

**Issue by nmathew87** [asotog/fabricjs-react#22]
npm install with react18 causes error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from fabricjs-react@1.0.8
npm ERR! node_modules/fabricjs-react
npm ERR!   fabricjs-react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by asotog** [comment]
we'll take care of this as soon as possible

**Comment by asotog** [comment]
@nmathew87 from version 1.1.1 React 18 is supported
