### ISSUE TITLE
Text disappears on edit / selected

### ISSUE THREAD

**Issue by eunicocornelius** [asotog/fabricjs-react#27]
Hey man, awesome package! The problem I'm facing is when using the addText() function. It just disappears when you click it to drag. You can still edit it, it just have a transparent fill for some reason. I also tried using manual plain fabricjs which results in the same thing. Is this a bug? 

The code I tried using:
```
editor?.addText("Editable Textbox");
editor?.canvas?.renderAll();
```
and

```
var textEditable = new fabric.Textbox("Editable Textbox", {
      width: 500,
      editable: true,
      fill: "black",
    });

    editor?.canvas.add(textEditable);
    editor?.canvas?.renderAll();
```

Am I just using it wrong? How do I use updateText() as well?

**Comment by eunicocornelius** [comment]
Turns out it was a useEffect bug

```
useEffect(() => {
    if (editor) {
      editor.canvas.backgroundColor = "white";
    }
    editor?.canvas?.renderAll();
    // editor.setFillColor("transparent"); // Cannot do this
  }, [editor]);
```

**Comment by asotog** [comment]
cool thanks @eunicocornelius I'm glad you resolved the issue
