### ISSUE TITLE
Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by tt-abetemadi** [asotog/fabricjs-react#33]
**current behavior**
Cannot read properties of null (reading 'useState')
<img width="513" alt="image" src="https://github.com/asotog/fabricjs-react/assets/93504194/fb5faac3-9202-4072-8114-218dcf61a70d">
**dependencies**

-  "fabric": "^5.3.0",
-  "fabricjs-react": "^1.2.0",
-  "react": "17.0.2",
-  "react-dom": "17.0.2",

**Comment by asotog** [comment]
is your runtime regular spa ? or using some kind of SSR ? based on the error, seems failing in the import of useState https://github.com/asotog/fabricjs-react/blob/master/src/lib/editor.tsx#L3
