### ISSUE TITLE
Fabricjs6 beta12 giving error for textbox

### ISSUE THREAD

**Issue by vimlesh1975** [asotog/fabricjs-react#34]
Hi
I use fabricjs-react with fabric.  With fabric version 5.3 it is ok , but with fabricjs beta version it is giving error like .
Cannot read properties of undefined (reading 'register')
    at Textbox._mouseDownHandle

https://codesandbox.io/s/gallant-hill-qgzjm3?file=/src/App.js

**Comment by asotog** [comment]
@vimlesh1975 seems the issue is when dragging right ? have you tried it without fabric react library, wondered if is an issue on beta version

**Comment by vimlesh1975** [comment]
Yes. The lower text is without fabric-react. And works ok.

**Comment by vimlesh1975** [comment]
Yes. The lower text is without fabric-react. And works ok.

**Comment by vimlesh1975** [comment]
Problem is in fabric.Textbox and fabric.IText.
It is ok with fabric.Text

**Comment by vimlesh1975** [comment]
Please make a version using fabric 6

**Comment by asotog** [comment]
thanks @vimlesh1975 let take action on this, this week

**Comment by asotog** [comment]
https://github.com/asotog/fabricjs-react/pull/45

**Comment by asotog** [comment]
check version 2.0.0

**Comment by vimlesh1975** [comment]
Thanks. It is working now.
