### ISSUE TITLE
Fix "exports" field in package.json for TypeScript typings resolution

### ISSUE THREAD

**Issue by Xy2002** [asotog/fabricjs-react#35]
### Description

When incorporating `fabricjs-react` into my project, TypeScript reported an error stating it couldn't find the type declarations for `fabricjs-react`. Upon inspecting the `package.json` of `fabricjs-react`, it seems that the "exports" field might not be configured properly to point TypeScript towards the type declarations.

### Expected Behavior

TypeScript should be able to recognize the type declarations provided by `fabricjs-react`.

### Actual Behavior

TypeScript reports an error about missing type declarations.

### Additional Context

Upon further investigation, a potential solution might be adjusting the "exports" field in `package.json` of `fabricjs-react`. Specifically, ensuring it points correctly to the `index.d.ts` file for types.

**Comment by asotog** [comment]
hi thanks for the help, already published v1.2.1
