### ISSUE TITLE
useFabricJSEditor hook returns undefined for editor

### ISSUE THREAD

**Issue by andrewmelnyk** [asotog/fabricjs-react#38]
Is it expected that the editor object returned is `undefined` to start? Is there a way to get that from the onReady callback which looks like it only returns the canvas element not the editor?

```
const { editor, onReady } = useFabricJSEditor();
```

![Screenshot 2024-01-09 at 4 43 08 PM](https://github.com/asotog/fabricjs-react/assets/1019709/fd4a8859-b289-4697-9b2d-10fcc76b8749)

**Comment by asotog** [comment]
is recommended to use optional chain, because the canvas has to mount before be able to use editor object

**Comment by asotog** [comment]
marking a closed, is expected behavior
