### ISSUE TITLE
Update to react 19

### ISSUE THREAD

**Issue by jraut** [asotog/fabricjs-react#48]
Hello, 

I just updated to react 19 which is right behind the corner. Ran into a problem:

`TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at <unknown> (path/node_modules/fabricjs-react/dist/fabricjs-react.es.js:318:15)
    at Or (path/node_modules/fabricjs-react/dist/fabricjs-react.es.js:759:4)
    at <unknown> (path/node_modules/fabricjs-react/dist/fabricjs-react.es.js:762:74)
    at <unknown> (path/node_modules/fabricjs-react/dist/fabricjs-react.es.js:763:3)`

**Comment by armedi** [comment]
I got similar issue today after upgrading to react 19

**Comment by armedi** [comment]
I got it working  with this build config changes https://github.com/asotog/fabricjs-react/compare/master...armedi:fabricjs-react:master?expand=1

You can try it with

```bash
npm i https://github.com/armedi/fabricjs-react/releases/download/v2.0.1/fabricjs-react-2.0.1.tgz
```

**Comment by armedi** [comment]
Hi @jraut, does this solve your problem?

**Comment by jraut** [comment]
This looks really good, thanks @armedi for taking it forward. I have not been able to try it out in a comprehensive manner yet. I wish I could, but updating to React 19 is coming "soon" and therefore I could not prioritise this more so far.

**Comment by asotog** [comment]
looks good thanks guys, new version published https://codesandbox.io/p/sandbox/flamboyant-wind-ff3x8
