### ISSUE TITLE
How to do drawing like on a whiteboard?

### ISSUE THREAD

**Issue by ct-gilford** [asotog/fabricjs-react#5]
Sorry but I can't seems to find documentations about this.

**Comment by asotog** [comment]
@ct-gilford when you get editor from the hook you can use the fabricjs canvas directly :
```
const { editor, onReady } = useFabricJSEditor()

...
editor.canvas.isDrawingMode = true;

...
```

**Comment by ct-gilford** [comment]
> @ct-gilford when you get editor from the hook you can use the fabricjs canvas directly :
> 
> ```
> const { editor, onReady } = useFabricJSEditor()
> 
> ...
> editor.canvas.isDrawingMode = true;
> 
> ...
> ```
> 
> ref: http://fabricjs.com/freedrawing

It works, thanks!
