### ISSUE TITLE
Touch Events Support

### ISSUE THREAD

**Issue by ct-gilford** [asotog/fabricjs-react#7]
I know it is possible to create [custom build](http://fabricjs.com/build/) of FabricJS that supports touch gestures but does fabricjs-react support it? I have tested touch events like `touch:gesture` but it's never fired.

**Comment by asotog** [comment]
Hi @ct-gilford as fabricjs is a peer dependency I think you can explore forking fabricjs, modify it and then from your project, point to the repo you have it

**Comment by ct-gilford** [comment]
> Hi @ct-gilford as fabricjs is a peer dependency I think you can explore forking fabricjs, modify it and then from your project, point to the repo you have it

I have not done this but what I did create the custom JS files from [here](http://fabricjs.com/build/) and put them in dist folder of fabricjs-react in node_modules. So now it's working.

**Comment by wrteam-sagar** [comment]
@asotog @ct-gilford 

I have created the cusom js file and also placed it in node_modules/fabricjs-react/dist folder as fabric.min.js name

but touch events are not firing up. can you please explain a little bit. How to do that properly ?

**Comment by asotog** [comment]
@wrteam-sagar I would recommend asking this on fabricjs seems v6 will also change the way modules are added https://github.com/fabricjs/fabric.js/issues/7832
