### ISSUE TITLE
Adding image adds multiple images one below another.  

### ISSUE THREAD

**Issue by azakero** [asotog/fabricjs-react#9]
Hi @asotog, I tested the code on the usage section to render an image on the canvas, but there are multiple images being rendered. Like a million. Am I doing something wrong or its a bug? Can you please check it out? Here's the sandbox: https://y0rq7.csb.app/ and here's the code:

```
import React from "react";
import { fabric } from "fabric";
import { FabricJSCanvas, useFabricJSEditor } from "fabricjs-react";

const App = () => {
  const { selectedObjects, editor, onReady } = useFabricJSEditor();

  fabric.Image.fromURL("https://i.imgur.com/8zvUjul.jpg", function (oImg) {
    editor?.canvas.add(oImg);
  });

  return (
    <div>
      <FabricJSCanvas className="sample-canvas" onReady={onReady} />
    </div>
  );
};

export default App;
```

**Comment by asotog** [comment]
@azakero yea I think documentation, is not properly describing you have to wrap the add image part inside useEffect:

```
useEffect(() => {
  fabric.Image.fromURL("https://i.imgur.com/8zvUjul.jpg", function (oImg) {
    editor?.canvas.add(oImg);
  });
}, [fabric, editor])
```

**Comment by azakero** [comment]
@asotog Oh man. I feel stupid now. Thanks a lot. However I had another question. Can I use all the features from the original FabricJS library in this one?

**Comment by asotog** [comment]
yea sure `editor?.canvas` is the original library so it is basically http://fabricjs.com/docs/fabric.Canvas.html

**Comment by azakero** [comment]
Thanks a lot mate. For this package and for your help.

**Comment by azakero** [comment]
> @azakero yea I think documentation, is not properly describing you have to wrap the add image part inside useEffect:
> 
> ```
> useEffect(() => {
>   fabric.Image.fromURL("https://i.imgur.com/8zvUjul.jpg", function (oImg) {
>     editor?.canvas.add(oImg);
>   });
> }, [fabric, editor])
> ```

@asotog Hey man, I just tried this but it is still the same. Would you please try it again and check?

**Comment by azakero** [comment]
@asotog Sorry to bother you again mate, but have you checked it yet?

**Comment by asotog** [comment]
Hey @azakero not yet will give a look later this week, I think you can add a flag for now with useState to know whether or not image is loaded

**Comment by azakero** [comment]
Okay. Thank you.

**Comment by acabhishek942** [comment]
I am facing a similar issue @azakero were you able to resolve this ??
